namespace HostIsle.Data.Models.Restaurants
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Identity;

    // Add profile data for application users by adding properties to the User class
    public class User : IdentityUser
    {
        public User()
        {
        }

        [DefaultValue("false")]
        public bool isRegistrationFinished { get; set; }

        [DefaultValue("false")]
        public bool FirstLogIn { get; set; }

        public int EmployerId { get; set; }

        public string EmployeeFullName { get; set; }

        public virtual ICollection<Order> EmployeeOrders { get; set; }

        public DateTime RegisteredOn { get; set; }

        public string AutoGeneratedPassword { get; set; }

        public string IdCard { get; set; }

        public int RestaurantId { get; set; }

        public virtual Restaurant Restaurant { get; set; }

        public virtual ICollection<UserReview> UserReviews { get; set; }

        public virtual ICollection<Reservation> Reservations { get; set; }

    }
}
